name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dunivivi/cloud-app:${{ github.sha }}  # Using commit SHA as the tag

      # Step 5: Set up kubectl
      - name: Set up kubectl
        run: |
          echo "Setting up kubectl..."
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > "$HOME/k3s.yaml"
          export KUBECONFIG="$HOME/k3s.yaml"
          
          # Debugging: Verify the KUBECONFIG and list available contexts
          echo "Kubeconfig file: $HOME/k3s.yaml"
          kubectl config get-contexts || echo "Failed to list contexts"

          # Debugging: Try switching to the default context
          kubectl config use-context default || echo "Context 'default' not found"
          
          # Debugging: Show the current context
          kubectl config current-context || echo "Failed to get current context"
          
          # Debugging: Get cluster info to verify connection
          kubectl cluster-info || echo "Failed to get cluster info"

      # Step 6: Update Deployment with the new image tag
      - name: Update Deployment with new image tag
        run: |
          echo "Updating deployment..."
          kubectl set image deployment/cloud-app cloud-app=dunivivi/cloud-app:${{ github.sha }} --record || echo "Failed to set image for deployment"
          
          # Debugging: Verify the updated deployment status
          kubectl rollout status deployment/cloud-app || echo "Failed to get deployment status"

      # Step 7: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          echo "Applying Kubernetes deployment..."
          kubectl apply -f docker/deploy.yml || echo "Failed to apply Kubernetes deployment"
          
          # Debugging: Verify the applied resources
          kubectl get deployments || echo "Failed to get deployments"
          kubectl get pods || echo "Failed to get pods"

