name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dunivivi/cloud-app:${{ github.sha }}

      - name: Set up kubectl
        run: |
          export KUBECONFIG="/Users/tudor/k3s.yaml"
          kubectl config use-context default

      - name: Update Deployment YAML with dynamic image tag
        run: |
          sed -i '' "s|dunivivi/cloud-app:.*|dunivivi/cloud-app:${{ github.sha }}|g" deploy.yml

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG="/Users/tudor/k3s.yaml"
          kubectl apply -f deploy.yml
