name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dunivivi/cloud-app:${{ github.sha }}

      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG_BASE64 }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config use-context default

      - name: Update Deployment with new image tag
        run: |
          kubectl set image deployment/cloud-app cloud-app=dunivivi/cloud-app:${{ github.sha }} --record

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f docker/deploy.yml  # Reference deploy.yml from the docker directory
